/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Beliefs__factory } from "./Beliefs__factory";
export { IBeliefs__factory } from "./IBeliefs__factory";
